# Generated by Django 3.2.4 on 2022-07-23 09:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from=models.CharField(blank=True, max_length=200, unique=True), unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('featured', models.BooleanField(default=False, help_text='Select this content for main menu')),
                ('sequence', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('sequence', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('content_image', models.ImageField(blank=True, upload_to='content_images/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('copyright_text', models.CharField(blank=True, max_length=120, null=True)),
                ('google_analytics_code', models.CharField(blank=True, help_text='Paste google analytics tracing code: ex. UA-69123876-4', max_length=50, null=True)),
                ('alexa_code', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Input your Facebook page url', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Input your Twitter page url', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Input your YouTube page url', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Input your LinkedIN page url', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Input your Instagram page url', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='username')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_home', models.BooleanField(help_text='Select this content for home page')),
                ('description', tinymce.models.HTMLField()),
                ('content_image', models.ImageField(upload_to='content_images/')),
                ('quote_text', models.TextField(blank=True, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('video_link', models.CharField(blank=True, help_text='Input YouTube Video Embed Code', max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('top_news', models.CharField(choices=[('S', 'Slider'), ('6', 'Top 6'), ('N', 'None')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(help_text='Select main category', on_delete=django.db.models.deletion.CASCADE, to='core.maincategory')),
                ('news_room', models.ForeignKey(blank=True, help_text='Select news room', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.newsroom')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
    ]
