# Generated by Django 3.2.4 on 2022-09-09 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220909_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog1',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 17, 15, 40, 415165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 17, 15, 40, 415165, tzinfo=utc)),
        ),
    ]
