# Generated by Django 3.2.4 on 2023-01-06 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20230106_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 15, 50, 52, 933754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 15, 50, 52, 931753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='home',
            field=models.BooleanField(default=False, help_text='select this blog for home page'),
        ),
    ]
