# Generated by Django 3.2.4 on 2023-01-06 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20230106_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.BooleanField(default=False, help_text='permission to edit or delete'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 15, 57, 5, 318338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 15, 57, 5, 317337, tzinfo=utc)),
        ),
    ]
